version: "3.7"

services:
  mel_app:
    build: ./mel_app/
    image: mel_dev
    container_name: mel_dev_container
    ports:
      - "3000:3000"
    depends_on:
      mel_db:
        condition: service_healthy

  mel_db:
    image: mariadb:11.0
    container_name: mel_dev_db
    env_file:
      - mel_db/pi.env
    ports:
      - "3306:3306"
    volumes:
      - ./mel_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "/usr/bin/mariadb --user=root --password=admin --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    container_name: mel_adminer
    ports:
      - "8080:8080"
