version: "3.7"

services:
  mel_app:
    build: ./mel_app/
    image: mel_dev
    container_name: mel_dev_container
    ports:
     - "3000:3000"

  mel_db:
    image: mariadb:11.0
    container_name: mel_dev_db
    env_file:
     - mel_db/pi.env
    ports:
     - "3306:3306"
    volumes:
     - ./mel_db/init.sql:/docker-entrypoint-initdb.d/init.sql

  mel_web_app:
    build: ./mel_web_app
    image: mel_web_app
    container_name: mel_web_dev_container
    ports:
     - "8080:80"
